/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) <2020-2025> Intel Corporation.
 */

/* Created 2018 by Keith Wiles @ intel.com */

#ifndef _RTE_LUA_UTILS_H_
#define _RTE_LUA_UTILS_H_

/**
 * @file
 *
 * Lua shell utility helpers: string trimming, console output, line reading,
 * error reporting, and Lua status checking.
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <signal.h>
#include <inttypes.h>
#include <sys/types.h>
#include <unistd.h>
#include <string.h>
#include <pthread.h>

#include <lua_config.h>

#define lua_c

#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Trim leading and trailing whitespace from @p str in place.
 *
 * @param str   String to trim. Modified in place.
 * @return      Pointer to the first non-whitespace character within @p str.
 */
char *lua_strtrim(char *str);

/**
 * Write a formatted string to stdout and flush.
 *
 * @param format   printf-style format string.
 * @param ...      Variable arguments for @p format.
 */
static inline void
lua_putstring(const char *format, ...)
{
    va_list ap;

    va_start(ap, format);
    vfprintf(stdout, format, ap);
    va_end(ap);

    fflush(stdout);
}

/**
 * Read one line of input from the Lua instance's stdin into its buffer.
 *
 * @param ld   Lua instance whose stdin and buffer are used.
 * @return     Pointer to ld->buffer on success, or NULL on EOF/error.
 */
static inline char *
lua_readline(luaData_t *ld)
{
    *ld->buffer = '\0';
    return fgets(ld->buffer, LUA_BUFFER_SIZE, lua_get_stdin(ld));
}

/**
 * Print a Lua error message to stderr, optionally prefixed by @p pname.
 *
 * @param pname   Programme name prefix, or NULL to omit.
 * @param msg     Error message string to print.
 */
static inline void
l_message(const char *pname, const char *msg)
{
    if (pname)
        lua_writestringerror("%s: ", pname);
    lua_writestringerror("%s\n", msg);
}

/**
 * Check @p status and, if it indicates an error, print the top-of-stack message.
 *
 * Assumes the error object is a string (as generated by Lua or msghandler).
 * Pops the error string from the stack before returning.
 *
 * @param L       Lua state.
 * @param status  Return value from a Lua protected call (e.g. lua_pcall).
 * @return        @p status unchanged.
 */
static inline int
report(lua_State *L, int status)
{
    if (status != LUA_OK) {
        const char *msg = lua_tostring(L, -1);

        l_message(lua_get_progname(), msg);
        lua_pop(L, 1); /* remove message */
    }
    return status;
}

#ifdef __cplusplus
}
#endif

#endif /* _LUA_SUPPORT_H_ */
