#   BSD LICENSE
#
#   Copyright(c) 2010-2014 Intel Corporation. All rights reserved.
#
#  SPDX-License-Identifier: BSD-3-Clause
#

include $(RTE_SDK)/mk/rte.vars.mk

DIRS-y += common
DEPDIRS-y = common

DIRS-y += lua
DEPDIRS-y += lua

DIRS-y += cli
DEPDIRS-y += cli

include $(RTE_SDK)/mk/rte.extsubdir.mk
